### ISSUE TITLE
Unable to set annotation process for IntelliJ

### ISSUE THREAD

**Issue by NawaMan** [NawaMan/FunctionalJ#1]
I use Eclipse for all my Java development and only use IntelliJ at work for TypeScript. Nothing against IntelliJ just that I've been using Eclipse for a long time. FunctionalJ types use annotation processing which I can set up find on Eclipse. I am unable to set it up for IntelliJ. Any one can help with this? Any help is appreciated. :-)

**Comment by xasx** [comment]
Here you should find the information you need:

https://www.baeldung.com/lombok-ide

Lombok just works the same way as your library. Thanks for sharing 👍 
Will also test some things out.

**Comment by NawaMan** [comment]
Hi xasx, Thank you for the link. I've tried something very similar (but the instruction from the library Immutables). It works at the first try but when I try again in another project, it does not work and I had no idea why ... as I don't use IntelliJ every day and might not know its ways.

Have you actually try that and get a good result? Let me know. If that is the case, then I can put the link for that in the doc and let's close this one until someone find the problem again.

Thanks :-D
